create database dbElectromesticos
GO

use dbElectromesticos
GO


CREATE TABLE CLIENTE (
CODCLI CHAR(4) , --IDENTITY(1,1),
NOMCLI VARCHAR(60),
APECLI VARCHAR(80),
EMACLI VARCHAR(80),
CELCLI CHAR(9) null,
DIRCLI VARCHAR(70),
ESTCLI CHAR(1),
 CONSTRAINT CODCLI_PK PRIMARY KEY (CODCLI)

)

CREATE TABLE VENDEDOR (
CODVEND CHAR(4), --IDENTITY(1,1),
NOMVEND VARCHAR(60),
APEVEND VARCHAR(80),
EMAVEND VARCHAR(80),
CELVEND CHAR(9),
DIRVEND VARCHAR(70),
ESTVEND CHAR(1),
CONSTRAINT CODVEND_PK PRIMARY KEY (CODVEND)
)

CREATE TABLE PRODUCTO(
CODPRO VARCHAR(5),
DESCPRO VARCHAR(80),
CATPRO CHAR(1),
PREPRO DECIMAL(8,2),
STOCKPRO INT,
ESTPRO CHAR(1),
CONSTRAINT CODPRO_PK PRIMARY KEY (CODPRO)
)


CREATE TABLE PROVEEDOR(
CODPROV CHAR(5),
RAZSOCPROV VARCHAR(90),
RUCPROV VARCHAR(11),
EMAPROV VARCHAR(70),
ESTPROV CHAR(1),
CONSTRAINT CODPROV_PK PRIMARY KEY (CODPROV)
)

CREATE TABLE VENTA(
CODVEN CHAR(5) ,
FECVEN DATETIME,
CODCLI CHAR(4),
CODVEND CHAR(4),
ESTVEN CHAR(1),
CONSTRAINT CODVEN_PK PRIMARY KEY (CODVEN)
)

CREATE TABLE VENTADETALLE(
IDVENDET INT IDENTITY(1,1),
CODVEN CHAR(5),
CODPRO VARCHAR(5),
CANTPRO INT,
CONSTRAINT IDVENDET_PK PRIMARY KEY (IDVENDET)
)


CREATE TABLE COMPRA(
CODCOM CHAR(5),
FECCOM DATETIME,
CODVEND CHAR(4),
CODPROV CHAR(5),
ESTCOM CHAR(1),
CONSTRAINT CODCOM_PK PRIMARY KEY (CODCOM)
)

CREATE TABLE COMPRADETALLE(
IDCOMDET INT IDENTITY(1,1),
CODCOM CHAR(5),
CODPRO VARCHAR(5),
CANTPRO INT,
CONSTRAINT IDCOMDET_PK PRIMARY KEY (IDCOMDET)
)



ALTER TABLE VENTA
ADD CONSTRAINT CODCLI_FK FOREIGN KEY (CODCLI) REFERENCES CLIENTE(CODCLI); 
ALTER TABLE VENTA
ADD CONSTRAINT CODVEND_FK FOREIGN KEY (CODVEND) REFERENCES VENDEDOR(CODVEND); 

ALTER TABLE VENTADETALLE
    ADD CONSTRAINT CODPRO_FK FOREIGN KEY (CODPRO)REFERENCES PRODUCTO(CODPRO);   
ALTER TABLE VENTADETALLE
    ADD CONSTRAINT CODVEN_FK FOREIGN KEY (CODVEN)REFERENCES VENTA(CODVEN); 

ALTER TABLE COMPRA
ADD CONSTRAINT CODPROV_FK FOREIGN KEY (CODPROV) REFERENCES PROVEEDOR(CODPROV); 
ALTER TABLE COMPRA
ADD CONSTRAINT CODVEND_FK FOREIGN KEY (CODVEND) REFERENCES VENDEDOR(CODVEND); 

ALTER TABLE COMPRADETALLE
    ADD CONSTRAINT CODPRO_FK FOREIGN KEY (CODPRO)REFERENCES PRODUCTO(CODPRO);   
ALTER TABLE COMPRADETALLE
    ADD CONSTRAINT CODCOM_FK FOREIGN KEY (CODCOM)REFERENCES COMPRA(CODCOM); 


INSERT INTO CLIENTE
VALUES
('CL01','Juana','Campos Ortiz','juana.campos@gmail.com','987485152','Av. Miraflores','A'),
('CL02','Sofía','Barrios Salcedo','sofia.barrrios@outlook.com','null','Jr. Huallaga','A'),
('CL03','Claudio','Pérez Luna','claudio.perez@outlook.com','984512147','Av. Libertadores','A'),
('CL04','Marcos','Ávila Manco','marcos.avila@yahoo.com','null','Calle Huallaga','A'),
('CL05','Anastacio','Salomon Inti','anastacio.salomon@gmail.com','null','Jr. San Martín','A');

SELECT * FROM CLIENTE


INSERT INTO VENDEDOR
VALUES
('VEN1','Gloria','Carrizales Paredes','gloria.carrizales@gmail.com','984574123','Calle Las Begonias','A'),
('VEN2','Gabriel','Lozado Lombardi','gabriel.lozado@gmail.com','974512368','Av. Los Girasoles','A'),
('VEN3','Gilberto','Martínez Guerra','gilberto.martinez@gmail.com','null','Jr. Palomares','A');

SELECT * FROM VENDEDOR


INSERT INTO PROVEEDOR
VALUES
('PRV01','LG Corporation','87542136951','informes@lg.com.pe','A'),
('PRV02','SONY','45213698741','informes@sony.com.pe','A'),
('PRV03','SAMSUNG','85321697661','informes@samsung.com.pe','A'),
('PRV04','OSTER SRL','55663214478','informes@oster.com.pe','A'),
('PRV05','ASUS','99663325478','informes@asus.com.pe','A');



INSERT INTO PRODUCTO
VALUES
('PRO01','Refrigerado LG Side By Side','1','4149','15','A'),
('PRO02','Refrigerado SBS 602L','1','3599','10','A'),
('PRO03','Refrigerado Top Mount 500 L','1','2799','8','A'),
('PRO04','TV SAMSUNG UHD 55"','2','1799','25','A'),
('PRO05','Televisor 65" LG UHD 4K','2','2999','20','A'),
('PRO06','TV CRYSTAL UHD 55"','2','2299','7','A'),
('PRO07','ASUS X415JA Core i3 10a Gen 14"','3','1099','17','A'),
('PRO08','Lenovo IdeaPad  5i Intel Core i7 14"','3','3099','10','A'),
('PRO09','Laptop HP 15-dw1085la Intel Core i3','3','1600','15','A'),
('PRO10','Galaxy A52 128GB','4','1200','25','A'),
('PRO11','iPhone 11 64 GB Morado','4','2600','30','A'),
('PRO12','Poco X3 GT 5G 256GB 8GB','4','1450','20','A');

SELECT * FROM PRODUCTO

SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[sp.VENTA]
	@CODVEN CHAR(5),
    @FECVEN DATETIME,
    @CODCLI char(4),
    @CODVEND char(4),
	@ESTVEN CHAR(1),
	@MODO CHAR(1)
	AS 
	IF @MODO = 'A'
	BEGIN 
	INSERT VENTA  VALUES 
	('VEN01','GETDATE()','CL01','VEN1','A'),
	('VEN02','GETDATE()','CL02','VEN2','A'),
	('VEN03','GETDATE()','CL03','VEN3','A');
	END
	
 CREATE PROCEDURE [dbo].[sp.VENTADETALLE]
	@IDVENDET INT,
	@CODVEN CHAR(5),
	@CODPRO VARCHAR(5),
	@CANTPRO INT,
	@COM CHAR(1)
	AS
	IF @COM = 'A'
	BEGIN

GO

--VISTAS

SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[VENTASTRANS]
AS SELECT V.FECVEN, V.TIPVEN, PER.NOMPER, PER.APEPER, U.NOMUSU, P.NOMPRO, D.CANTDETVEN
FROM dbo.DETALLEVENTA AS D
INNER JOIN dbo.PRODUCTO AS P ON P.IDPRO = D.IDPRO
INNER JOIN dbo.VENTA AS V ON V.IDVEN = D.IDVEN
INNER JOIN dbo.USUARIO AS U ON V.IDUSU = U.IDUSU
INNER JOIN  dbo.PERSONA AS PER ON PER.IDPER = V.IDPER
GO